import Head from 'next/head'
import Banner from '../components/Banner'
import Navbar from '../components/Navbar'
import Mentors from '../components/Mentors';

export default function Home() {
  return (
    <div className="h-screen w-screen overflow-hidden">
      <Head>
        <title>Ensight | Educational Insight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-full bg-sky-100'>
        <Navbar/>
        <Banner/>
        {/* <Mentors></Mentors> */}
      </main>
      
    </div>
  )
}
